const ROLES = Object.freeze({
  ADMIN: 'admin',
  RECEPTIONIST: 'receptionist',
  TEACHER: 'teacher',
  STUDENT: 'student',
  PARENT: 'parent',
});

const CLASS_LEVELS = Object.freeze(['11th', '12th', 'CET']);

const PERMISSIONS = Object.freeze({
  // User management
  USER_CREATE: [ROLES.ADMIN],
  USER_UPDATE: [ROLES.ADMIN],
  USER_DELETE: [ROLES.ADMIN],
  USER_READ_ALL: [ROLES.ADMIN],

  // Pricing
  PRICING_MANAGE: [ROLES.ADMIN],

  // Payouts
  PAYOUT_MANAGE: [ROLES.ADMIN],
  PAYOUT_VIEW_OWN: [ROLES.TEACHER],

  // Enrollments
  ENROLLMENT_MANAGE: [ROLES.ADMIN, ROLES.RECEPTIONIST],

  // Fee
  FEE_COLLECT: [ROLES.ADMIN, ROLES.RECEPTIONIST],
  FEE_VIEW_OWN: [ROLES.STUDENT],

  // Timetable
  TIMETABLE_MANAGE: [ROLES.ADMIN, ROLES.RECEPTIONIST],
  TIMETABLE_VIEW: [ROLES.TEACHER, ROLES.STUDENT],

  // Attendance
  ATTENDANCE_MARK: [ROLES.ADMIN, ROLES.TEACHER],
  ATTENDANCE_VIEW_OWN: [ROLES.STUDENT],

  // Tests
  TEST_MANAGE: [ROLES.ADMIN],
  TEST_VIEW: [ROLES.TEACHER, ROLES.STUDENT],
  TEST_RESULTS_INPUT: [ROLES.ADMIN, ROLES.TEACHER],
  TEST_RESULTS_VIEW_OWN: [ROLES.STUDENT],

  // Study Materials
  STUDY_MATERIAL_MANAGE: [ROLES.ADMIN],
  STUDY_MATERIAL_UPLOAD: [ROLES.TEACHER],
  STUDY_MATERIAL_DOWNLOAD: [ROLES.STUDENT],

  // Push Notifications
  NOTIFICATION_SEND: [ROLES.ADMIN],
  NOTIFICATION_RECEIVE: [ROLES.TEACHER, ROLES.STUDENT, ROLES.RECEPTIONIST, ROLES.PARENT],

  // Parent portal
  PARENT_VIEW_CHILDREN: [ROLES.PARENT],
});

module.exports = { ROLES, CLASS_LEVELS, PERMISSIONS };
